
# makefile for making myexpand
# author: Emil Schneider
myexpand: myexpand.c
	gcc myexpand.c -std=c99 -pedantic -Wall -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_SVID_SOURCE -D_POSIX_C_SOURCE=200809L -g -o myexpand
clean:
	rm -rf myexpand myexpand.o
