#@author= Julia Liepold, 11807886
#@name= ispalindrom

all : ispalindrom

ispalindrom : ispalindrom.c
	gcc -std=c99 -pedantic -Wall -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_SVID_SOURCE -D_POSIX_C_SOURCE=200809L -g ispalindrom.c -o ispalindrom

clean : 
	rm -f ispalindrom
