/**
 * @file supervisor.c
 * @author Daniel Blattner <e12020646@students.tuwien.ac.at>
 * @date 09.11.2021
 *
 * @brief The programm supervise multiple generator and recieve their solutions.
 *
 * First of all the supervisor create the shared memory and semaphores. This must happen
 * before the first generator tries to open the shared memory and semaphores or else an 
 * error occurs. The programm task is to read solution (generated by the generators) from
 * the shared memory and the best solution is saved. When the supervisor terminated, it 
 * signals the generators to terminate as well. 
 *
**/

#include "circularbuffer.h"

/** Name of programm as defined in argv[0] **/
static char *progName;

/** Shared ressources of the supervisor **/
static SharedResource res;

/**
 * @brief The function will be executed if an SIGINT or SIGTERM is
 * recived. The global variable quit will be set to 1, which indicates
 * the programms to terminate. 
 * @param signal The signal, which activated the handler.
**/
static void handle_signal(int signal)
{
   //Signal the generators to terminate
   res.buffer->termGen = 1;
}

/**
 * @brief This function configures the signals SIGINT and SIGTERM to execute
 * the function handle_signal. 
 * @details If an error occures, a error message is printed and the program
 * exits with an EXIT_FAILURE.
**/
static void initSignalHandler(void)
{
   struct sigaction sTerm;
   if (sigemptyset(&sTerm.sa_mask) == -1){
      printErrorMsgExit(progName, "Could not initialize signal handeling");
   }
   sTerm.sa_handler = handle_signal;
   sTerm.sa_flags = 0;
   if(sigaction(SIGINT, &sTerm, NULL) == -1 || sigaction(SIGTERM, &sTerm, NULL) == -1){
      printErrorMsgExit(progName, "Could not initialize signal handeling");
   }
}

/**
 * @brief This function prints a solution (its lengh and edges) to stdout. If a
 * solution contains not edges, it prints that the graph is acyclic.
 * @details global variables: progName
 * @param bestSolution The solution which should be printed. 
**/
static void printBestSolution(EdgeArray bestSolution)
{
   assert(bestSolution.len < DATA_LIMIT);
   
   //Solution is perfect
   if(bestSolution.len == 0){
      printf("[%s] The graph is acyclic!\n", progName);
      return;
   }

   //Print solution with edges
   printf("[%s] Solution with %d edges: ", progName, bestSolution.len);
   for(int i=0; i<bestSolution.len; i++){
      printf("%d-%d ", bestSolution.array[i].start, bestSolution.array[i].end);
   }
   printf("\n");
}

/**
 * @brief The programm starts here. First of all the signals SIGINT and SIGTERM are
 * configured to get handeld by the handle_signal function. Then the shared memory
 * and semaphores are created. After that the supervisor reads from the shared memory
 * the solutions. If a better solution was found, the supervisor safes it and prints it
 * to stdout. When a perfect solution or a signal was recieved the supervisor terminates
 * and signals the generators to terminate as well.  
 * @details global variables: progName
 * @param argc The argument counter. 
 * @param argv The argument vector.
 * @return Returns EXIT_SUCCESS.
**/
int main(int argc, char *argv[])
{
   progName = argv[0];

   //Configure signals
   initSignalHandler();

   //Create/map shared memory and semaphores
   initSharedResource(progName, &res, true);

   EdgeArray bestSolution = {.len = DATA_LIMIT}; 
   do{
      //Read new solution
      EdgeArray data;
      if(!readEdgeArray(progName, &res, &data)) break;
      
      //Better solution found
      if(data.len < bestSolution.len){
         memcpy(&bestSolution, &data, sizeof(EdgeArray));
         printBestSolution(bestSolution);
      }

   }while(bestSolution.len != 0 && res.buffer->termGen != 1);

   //Signal the generators to terminate
   res.buffer->termGen = 1;
   sem_post(res.writerdy);
   //Close/unmap/unlink shared memory and semaphores
   destroySharedResource(progName, &res, true);

   return EXIT_SUCCESS;
}